name: Commit Calendar
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Current year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_calendar: yes
          commits_authoring: Dmitrii Lipko, dmitrii.lipko, dmitrii.lipko@tiqets.com
          
      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
          commits_authoring: Dmitrii Lipko, dmitrii.lipko, dmitrii.lipko@tiqets.com 